title: dr.
author: yw-fang
email: xxxxxxx
description: > # this means to ignore newlines until "baseurl:"
  "Hello, welcome to visit me!" 
  You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: mytiwtter
github_username:  mygithub

show_excerpts: true # set to false to remove excerpts on the homepage

yw-fang-jekyll
theme: jekyll-theme-minimal

